FROM node:14.17.4 As development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install rimraf

RUN npm install

COPY . .

RUN npm run build

FROM node:14.17.4 as production

ARG NODE_ENV=production

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY --from=development /usr/src/app/dist ./dist

COPY .env .env

EXPOSE 5002

CMD ["node", "dist/main"]